Clean up non-ANSI displays for CHAINS
wwivbbs/wwiv pull request #1530
Opened 2023-01-20 09:26 UTC by ericpareja

Don't display hi-bit line chars to non-ANSI users. Replace with ASCII chars.
Fixes #1529

2023-01-20 20:51 UTC, wwiv requested changes

2023-01-20 20:51 UTC, wwiv commented on bbs/chains.cpp
> +	bout.bpla(fmt::sprintf("+--+----------------------------+-----+--+----------------------------+-----+"), &abort);
there are no params here, remove the fmt::sprintf wrapper

2023-01-20 20:51 UTC, wwiv commented on bbs/chains.cpp
> +	bout.bpla(fmt::sprintf("+--+----------------------------------+--+----------------------------------+"), &abort);
remove sprintf (again)

2023-01-20 20:51 UTC, wwiv commented on bbs/chains.cpp
> +    auto bar = fmt::sprintf("|#%d%s", FRAME_COLOR, okansi() ? "\xB3": "|") ;
please use format
"|#{:d}{}" woud be right to use.  The :d just to make sure it treats it as an int

2023-01-20 20:51 UTC, wwiv commented on bbs/chains.cpp
> +	bout.bpla(fmt::sprintf("+--+----------------------------+-----+--+----------------------------+-----+"), &abort);
remove the fmt:sprintf, there's no parameters here

2023-01-20 20:51 UTC, wwiv commented on bbs/chains.cpp
> +      auto bar = fmt::sprintf("|#%d%s", FRAME_COLOR, okansi() ? "\xB3": "|") ;
please add const

2023-01-20 20:51 UTC, wwiv commented on bbs/chains.cpp
> +          bout.bpla(fmt::sprintf("  %s                                  %s",bar,bar), &abort);
please use fmt::format

2023-01-20 21:08 UTC, ericpareja commented on bbs/chains.cpp
> +      auto bar = fmt::sprintf("|#%d%s", FRAME_COLOR, okansi() ? "\xB3": "|") ;
auto const?

2023-01-20 22:29 UTC, ericpareja reviewed
Tidied up the other occurrences of fmt::sprintf() to fmt::format() and tested build on Debian 10.13.

2023-01-21 00:03 UTC, wwiv approved these changes

2023-01-21 00:03 UTC, merged